### ISSUE TITLE
kobuki examples with latest release of VisualStates

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates-examples#13]
As kobuki example is developed using an older release of VisualStates tool, with the following commit https://github.com/JdeRobot/VisualStates/commit/1172b983148322c96f2b7483b474b8f85396cbf4  
the XMLs are outdated. Update examples but with the latest release of VSTool.

**Comment by sudo-panda** [comment]
I would like to work on this issue.

**Comment by sudo-panda** [comment]
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sudo-panda/Workspaces/jde_robot/src/VisualStates/src/visualstates/codegen/python/state.py", line 101, in run
    self.currentState.runCode()
  File "/home/sudo-panda/Workspaces/jde_robot/src/kbag/kbag.py", line 110, in runCode
    self.globalNamespace.publishturtlebotROS_mobile_base_commands_velocity(velCommand)
AttributeError: GlobalNamespace instance has no attribute 'publishturtlebotROS_mobile_base_commands_velocity'

```
Is this the error that is to be resolved?

**Comment by pushkalkatara** [comment]
Hi @sudo-panda . yes, the example is not made according to the new updates in visualstates. the behavior would be the same with the logic.
