### ISSUE TITLE
prius_overtake error

### ISSUE THREAD

**Issue by sundyCoder** [JdeRobot/VisualStates-examples#19]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/visualstates/codegen/python/state.py", line 93, in run
    if tran.checkCondition():
  File "prius_overtake.py", line 274, in checkCondition
    self.namespace.car_in_front()
  File "prius_overtake.py", line 94, in car_in_front
    left_laser = self.globalNamespace.front_left_laser
AttributeError: GlobalNamespace instance has no attribute 'front_left_laser'

**Comment by pushkalkatara** [comment]
Hi @sundyCoder , Could you please check whether the topic /prius/front_left_laser/scan is being published by Gazebo?
